CREATE TABLE ALT_MAADB_FEELING(
  NAME VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_FEELING PRIMARY KEY (NAME)
);

CREATE TABLE ALT_MAADB_LEMMA(
  NAME VARCHAR2(200) NOT NULL,
  FEELING VARCHAR2(20) NOT NULL,
  PERCENTAGE NUMBER,
  FREQUENCY NUMBER,
  CONSTRAINT PK_LEMMA PRIMARY KEY (NAME, FEELING),
  CONSTRAINT FK_FEELING
    FOREIGN KEY (FEELING)
    REFERENCES ALT_MAADB_FEELING(NAME)
);

CREATE TABLE ALT_MAADB_LEXICAL_RESOURCE(
  NAME VARCHAR2(200) NOT NULL,
  FEELING VARCHAR2(20) NOT NULL,
  LEMMA VARCHAR2(200) NOT NULL,
  VALUE varchar2(100),
  /*CONSTRAINT PK_FEELING PRIMARY KEY (NAME,FEELING,LEMMA),*/
  CONSTRAINT FK_LEMMA
    FOREIGN KEY (LEMMA,FEELING)
    REFERENCES ALT_MAADB_LEMMA(NAME,FEELING)
);

create table ALT_MAADB_HASHTAG
(
    FEELING VARCHAR2(255),
    HASHTAG VARCHAR2(255),
    COUNT   NUMBER(19) not null,
    CONSTRAINT PK_HASHTAG PRIMARY KEY (FEELING,HASHTAG),
    CONSTRAINT FK_FEELING_HASHTAG
        FOREIGN KEY (FEELING)
        REFERENCES ALT_MAADB_FEELING(NAME)
);

create table ALT_MAADB_SYMBOL
(
    FEELING  VARCHAR2(255),
    SYMBOL   VARCHAR2(255),
    ALIAS    VARCHAR2(255),
    HTML_HEX VARCHAR2(255),
    COUNT    NUMBER(19) not null,
    CONSTRAINT PK_SYMBOL PRIMARY KEY (FEELING,ALIAS),
    CONSTRAINT FK_FEELING_SYMBOL
        FOREIGN KEY (FEELING)
        REFERENCES ALT_MAADB_FEELING(NAME)
);
