CREATE TABLE ALT_MAADB_FEELING(
  NAME VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_FEELING PRIMARY KEY (NAME)
);

CREATE TABLE ALT_MAADB_LEMMA(
  NAME VARCHAR2(200) NOT NULL,
  FEELING VARCHAR2(20) NOT NULL,
  PERCENTAGE NUMBER,
  FREQUENCY NUMBER,
  CONSTRAINT PK_LEMMA PRIMARY KEY (NAME, FEELING),
  CONSTRAINT FK_FEELING
    FOREIGN KEY (FEELING)
    REFERENCES ALT_MAADB_FEELING(NAME)
);

CREATE TABLE ALT_MAADB_LEXICAL_RESOURCE(
  NAME VARCHAR2(200) NOT NULL,
  FEELING VARCHAR2(20) NOT NULL,
  LEMMA VARCHAR2(200) NOT NULL,
  VALUE varchar2(100),
  CONSTRAINT FK_LEMMA
    FOREIGN KEY (LEMMA,FEELING)
    REFERENCES ALT_MAADB_LEMMA(NAME,FEELING)
);

delete from ALT_MAADB_LEXICAL_RESOURCE;
delete from ALT_MAADB_LEMMA;
delete from ALT_MAADB_FEELING;

SELECT *
FROM (select NAME, FEELING, LEMMA, COUNT(*) AS COUNT FROM ALT_MAADB_LEXICAL_RESOURCE GROUP BY NAME, FEELING, LEMMA)
WHERE COUNT>1
ORDER BY 1,2,3 
